default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - pre-rebase
  - pre-push
default_stages:
  - pre-commit
  - pre-merge-commit
  - pre-rebase
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        files: ".py$"
        pass_filenames: true
      - id: ruff
        name: ruff
        language: system
        entry: poetry run ruff check --fix
        files: ".py$"
        pass_filenames: true
      - id: black
        name: black
        language: system
        entry: poetry run black
        files: ".py$"
        pass_filenames: true
      - id: pyright
        name: pyright
        language: system
        entry: poetry run pyright
        pass_filenames: false
      - id: pytest
        name: pytest
        language: system
        entry: poetry run pytest
        pass_filenames: false
        stages:
          - pre-push
